repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending

  # Can't get this to work on nixos for some reason at present
  #- repo: https://github.com/bridgecrewio/checkov
  #  rev: 2.3.314
  #  hooks:
  #    - id: checkov

  #- repo: https://github.com/tenable/terrascan
  #  rev: v1.18.1
  #  hooks:
  #    - id: terraform-pre-commit

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_checkov
        args:
          - --args=--quiet
      - id: terraform_tflint
      - id: terraform_tfsec
        args:
          - --args=--no-code
          - --args=--concise-output
